version: 2

project_name: go-viya

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - skip: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: dingdayu
    name: go-viya
  prerelease: auto
  mode: replace
